site_name: "mkdocs<span>flux</span>"

watch:
  - mkdocs_flux

nav:
  - Home: index.md
  - Manual:
    - Basics: manual/basics.md
    - Markdown: manual/markdown.md
    - BibTeX: manual/bibtex.md
    - Docstring: manual/docstring.md
  - About: about.md

theme:
    name: flux

plugins:
  - bibtex:
      bib_file: "docs/refs.bib"

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
repo_url: https://github.com/yqshao/mkdocs-flux
repo_name: yqshao/mkdocs-flux
